// flow-typed signature: 81aac54d7c3f492eeba9cfee8e3da87f
// flow-typed version: <<STUB>>/bunyan-format_v^0.2.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bunyan-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bunyan-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bunyan-format/example/bunyan-string-level' {
  declare module.exports: any;
}

declare module 'bunyan-format/example/inspect' {
  declare module.exports: any;
}

declare module 'bunyan-format/example/json' {
  declare module.exports: any;
}

declare module 'bunyan-format/example/long' {
  declare module.exports: any;
}

declare module 'bunyan-format/example/short' {
  declare module.exports: any;
}

declare module 'bunyan-format/example/simple' {
  declare module.exports: any;
}

declare module 'bunyan-format/lib/format-record' {
  declare module.exports: any;
}

declare module 'bunyan-format/test/short' {
  declare module.exports: any;
}

declare module 'bunyan-format/test/simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bunyan-format/example/bunyan-string-level.js' {
  declare module.exports: $Exports<'bunyan-format/example/bunyan-string-level'>;
}
declare module 'bunyan-format/example/inspect.js' {
  declare module.exports: $Exports<'bunyan-format/example/inspect'>;
}
declare module 'bunyan-format/example/json.js' {
  declare module.exports: $Exports<'bunyan-format/example/json'>;
}
declare module 'bunyan-format/example/long.js' {
  declare module.exports: $Exports<'bunyan-format/example/long'>;
}
declare module 'bunyan-format/example/short.js' {
  declare module.exports: $Exports<'bunyan-format/example/short'>;
}
declare module 'bunyan-format/example/simple.js' {
  declare module.exports: $Exports<'bunyan-format/example/simple'>;
}
declare module 'bunyan-format/index' {
  declare module.exports: $Exports<'bunyan-format'>;
}
declare module 'bunyan-format/index.js' {
  declare module.exports: $Exports<'bunyan-format'>;
}
declare module 'bunyan-format/lib/format-record.js' {
  declare module.exports: $Exports<'bunyan-format/lib/format-record'>;
}
declare module 'bunyan-format/test/short.js' {
  declare module.exports: $Exports<'bunyan-format/test/short'>;
}
declare module 'bunyan-format/test/simple.js' {
  declare module.exports: $Exports<'bunyan-format/test/simple'>;
}
